'''x = input("Enter a name: ")

upper = 0
lower = 0

for ch in x:
    if "A" <= ch <= "Z":
        upper += 1
    elif "a" <= ch <= "z":
        lower += 1

print("Uppercase:", upper)
print("Lowercase:", lower)'''

'''x = "CAT"

for ch in x:
    print(ch)

print(ch)'''

'''for i in [5, 10, 15]:
    print(i)

print("Final:", i)'''
'''for i in [10, 20, 30]:
    pass

print(i)'''
x = input("Enter a string: ")

count = 0

for ch in x:
    

    print("Digits:", count)
